import datetime
import time
print("Please be ready to type the text in 3 seconds!")
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
time.sleep(1)
print("Start!")
time.sleep(0.1)
before=datetime.datetime.now()
text=input("Type here:")
after=datetime.datetime.now()
passed_time=(after-before)
time=round(passed_time.total_seconds(),2)
length=len(text)
word=len(text.split())
character_speed=round(length/time,2)
word_speed=round(word/time,2)
print("You type {} character and {} words.It took {} seconds.This mean you can write {} characters and {} words in 1 second.".format(length,word,time,character_speed,word_speed))